import { promises as fs } from 'fs';
import path from 'path';

const isProd = process.env.NODE_ENV === 'production';

const postsDir = isProd
  ? path.resolve(process.cwd(), 'dist/data/posts')
  : path.resolve(process.cwd(), 'server/data/posts');

const BASE_URL = process.env.BASE_URL || 'http://localhost:5173';
const DELAY_MS = 8000; // 8 seconds between calls to avoid OpenAI rate limits

interface Editor {
  id: number;
  name: string;
}

interface Gap {
  date: string;
  editorId: number;
  editorName: string;
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes('--dry-run');
  const daysBack = parseInt(args.find((a) => !a.startsWith('--')) || '7', 10);

  // Load editors
  const editorsPath = path.resolve(process.cwd(), 'server/data/editors.json');
  const editorsData = JSON.parse(await fs.readFile(editorsPath, 'utf-8'));
  const editors: Editor[] = editorsData.editors;

  // Generate date range (exclude today since posts for today are generated by cron throughout the day)
  const dates: string[] = [];
  const today = new Date();
  for (let i = daysBack; i >= 1; i--) {
    const date = new Date(today);
    date.setDate(date.getDate() - i);
    dates.push(date.toISOString().slice(0, 10));
  }

  console.log(`\n🔍 Scanning for gaps: ${dates[0]} to ${dates[dates.length - 1]} (${daysBack} days)`);
  console.log(`📂 Posts directory: ${postsDir}`);
  if (dryRun) console.log('⚠️  DRY RUN mode — no API calls will be made\n');
  else console.log('');

  // Build set of existing date-editor combinations
  const existing = new Set<string>();

  for (const dateStr of dates) {
    const [year, month, day] = dateStr.split('-');
    const dayDir = path.join(postsDir, year, month, day);

    try {
      const files = await fs.readdir(dayDir);
      for (const file of files) {
        if (!file.endsWith('.json')) continue;
        const hour = parseInt(file.slice(11, 13), 10);
        const editorId = hour + 1;
        existing.add(`${dateStr}|${editorId}`);
      }
    } catch {
      // Directory doesn't exist
    }
  }

  // Find gaps
  const gaps: Gap[] = [];
  for (const dateStr of dates) {
    for (const editor of editors) {
      const key = `${dateStr}|${editor.id}`;
      if (!existing.has(key)) {
        gaps.push({ date: dateStr, editorId: editor.id, editorName: editor.name });
      }
    }
  }

  if (gaps.length === 0) {
    console.log('✅ No gaps found! All editors have posts for all dates.');
    return;
  }

  console.log(`📊 Found ${gaps.length} gaps to fill\n`);

  // Group by date for efficient processing
  const gapsByDate = new Map<string, Gap[]>();
  for (const gap of gaps) {
    if (!gapsByDate.has(gap.date)) {
      gapsByDate.set(gap.date, []);
    }
    gapsByDate.get(gap.date)!.push(gap);
  }

  let filled = 0;
  let failed = 0;
  let skipped = 0;

  for (const [date, dateGaps] of gapsByDate) {
    console.log(`\n📅 ${date} — ${dateGaps.length} gaps:`);

    for (const gap of dateGaps) {
      const url = `${BASE_URL}/api/generate-posts?date=${gap.date}&editorId=${gap.editorId}`;

      if (dryRun) {
        console.log(`   [DRY] Would call: ${gap.editorName} (#${gap.editorId})`);
        skipped++;
        continue;
      }

      process.stdout.write(`   🚀 ${gap.editorName} (#${gap.editorId})... `);

      try {
        const response = await fetch(url);
        const data = await response.json() as { success: boolean; error?: string };

        if (data.success) {
          console.log('✅');
          filled++;
        } else {
          console.log(`❌ ${data.error || 'Unknown error'}`);
          failed++;
        }
      } catch (err) {
        const message = err instanceof Error ? err.message : 'Network error';
        console.log(`❌ ${message}`);
        failed++;
      }

      // Wait between calls
      await sleep(DELAY_MS);
    }
  }

  console.log('\n═══════════════════════════════════════════════════════════════');
  if (dryRun) {
    console.log(`📊 Summary (DRY RUN): ${skipped} gaps would be filled`);
  } else {
    console.log(`📊 Summary: ✅ ${filled} filled, ❌ ${failed} failed, Total: ${gaps.length}`);
  }
  console.log('═══════════════════════════════════════════════════════════════\n');
}

main().catch((err) => {
  console.error('❌ Error:', err);
  process.exit(1);
});
